version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: taskmaster-db
    restart: unless-stopped
    volumes:
      - ./mysql/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - taskmaster
  web:
    image: nginx:1.19.2
    container_name: taskmaster-web
    restart: unless-stopped
    volumes:
      - ${API_PATH}:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "${API_PORT}:80"
    depends_on:
      - api
    networks:
      - taskmaster
  api:
    image: taskmaster-api
    container_name: taskmaster-api
    restart: unless-stopped
    build:
      args:
        user: ${API_USER}
        uid: ${API_UID}
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ${API_PATH}:/var/www
    depends_on:
      - db
    networks:
      - taskmaster

networks:
  taskmaster:
    driver: bridge